name: CI
on:
  workflow_dispatch:
  push:
  pull_request:
  
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI"
  
  release:
    needs: ci
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ startsWith(github.repository, 'maybeec/') && github.ref == 'refs/heads/main' }}
    environment:
      name: production
    outputs:
      released: ${{ steps.release.outputs.released }}
    steps:
      - id: release
        run: |
          # set output to have an indicator whether the deployment was rejected or the script failed
          echo "::set-output name=released::false"
          #exit 1
          echo "::set-output name=released::true"      
  
  github-release:
    needs: release
    runs-on: ubuntu-latest
    if: needs.release.outputs.released == 'true'
    steps:
      - uses: devonfw-actions/create-github-release@main
        with:
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
          release_version: 'v2021.01.001'
