name: CI
on:
  workflow_dispatch:
  push:
  pull_request:
  
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI"
  
  release:
    needs: ci
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ startsWith(github.repository, 'maybeec/') && github.ref == 'refs/heads/main' }}
    environment:
      name: production
    outputs:
      released: ${{ steps.release.released }}
    steps:
      - id: release
        run: |
          # set output to have an indicator whether the deployment was rejected or the script failed
          echo "::set-output name=released::false"
          exit 1 && echo "Release"
          echo "::set-output name=released::true"
      #- name: Skipped Release
      #  if: failure() && steps.release.outputs.ran-release-script == true
      #  id: release-status
      #  run: echo "::set-output name=released::"${{ steps.release.outcome == 'success' && steps.release.outputs.ran-release-script == true }}
      - name: https://github.com/actions/toolkit/issues/399
        if: ${{ failure() }}
        run: |
          echo "::warning ::Failed"
  
  skipped-release:
    runs-on: ubuntu-latest
    needs: release
    # if: always() && (needs.release.result == 'failure') && (needs.release.outputs.released == '')
    steps:
      - run: |
          echo "Result: "${{ needs.release.result }}
          echo "Output: "${{ needs.release.outputs.released }}
      
  
  after-release:
    needs: release
    uses: maybeec/gha-test/.github/workflows/post-release-workflow.yml@main
    with:
      SKIP: ${{ needs.ci.outputs.released != true }}
