name: Release

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.repository.full_name == 'maybeec/gha-test'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.workflow_run.conclusion }}
          echo ${{ github.event.workflow_run.repository.full_name }}
          echo ${{github.event.action}}
          echo ${{github.event.repository.full_name}}
