name: Release

on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types:
      - completed

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.repository.full_name == 'devonfw/cobigen'
    runs-on: ubuntu-latest
    steps:
      - run: echo released
